### ISSUE TITLE
Dojo de React

### ISSUE THREAD

**Issue by mateus-lm** [fga-eps-mds/2023.2-SINDPOL-DOC#17]
Dojo de react, html e css.

**Comment by matheuscvp** [comment]
Dojo realizado no dia 11/10/2023, disponível pelo [Link](https://unbbr-my.sharepoint.com/:v:/g/personal/190055201_aluno_unb_br/EUoBsD45X31Gpxmb8q7hSRYBqh74qqnKMpnRsff-T53qyQ?e=scykow&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZyIsInJlZmVycmFsQXBwUGxhdGZvcm0iOiJXZWIiLCJyZWZlcnJhbE1vZGUiOiJ2aWV3In19)
